-- Create Database
CREATE DATABASE [INDIAN BANK];
GO

USE [INDIAN BANK];
GO

-- Create REGION MASTER table
CREATE TABLE REGION_MASTER (
    RID INTEGER PRIMARY KEY,
    REGION_NAME CHAR(6) NOT NULL
);
GO

-- Create PRODUCT MASTER table
CREATE TABLE PRODUCT_MASTER (
    PID CHAR(2) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(25) NOT NULL
);
GO

-- Create BRANCH MASTER table
CREATE TABLE BRANCH_MASTER (
    BRID CHAR(3) PRIMARY KEY,
    BRANCH_NAME VARCHAR(30) NOT NULL,
    BRANCH_ADDRESS VARCHAR(50) NOT NULL,
    RID INT NOT NULL,
    CONSTRAINT FK_BRANCH_REGION FOREIGN KEY (RID) REFERENCES REGION_MASTER(RID)
);
GO

-- Create USER MASTER table
CREATE TABLE USER_MASTER (
    USERID INTEGER PRIMARY KEY,
    USER_NAME VARCHAR(30) NOT NULL,
    DESIGNATION CHAR(1) NOT NULL,
    CONSTRAINT CHK_DESIGNATION CHECK (DESIGNATION IN ('M', 'T', 'C', 'O'))
);
GO

-- Create ACCOUNT MASTER table
CREATE TABLE ACCOUNT_MASTER (
    ACID INTEGER PRIMARY KEY,
    NAME VARCHAR(40) NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL,
    BRID CHAR(3) NOT NULL,
    PID CHAR(2) NOT NULL,
    DATE_OF_OPENING DATETIME NOT NULL,
    CLEAR_BALANCE MONEY NULL,
    UNCLEAR_BALANCE MONEY NULL,
    STATUS CHAR(1) NOT NULL DEFAULT 'O',
    CONSTRAINT FK_ACCOUNT_BRANCH FOREIGN KEY (BRID) REFERENCES BRANCH_MASTER(BRID),
    CONSTRAINT FK_ACCOUNT_PRODUCT FOREIGN KEY (PID) REFERENCES PRODUCT_MASTER(PID),
    CONSTRAINT CHK_STATUS CHECK (STATUS IN ('O', 'I', 'C'))
);
GO

-- Create TRANSACTION MASTER table
CREATE TABLE TRANSACTION_MASTER (
    TRANSACTION_NUMBER INTEGER IDENTITY(1,1) PRIMARY KEY,
    DATE_OF_TRANSACTION DATETIME NOT NULL,
    ACID INTEGER NOT NULL,
    BRID CHAR(3) NOT NULL,
    TXN_TYPE CHAR(3) NOT NULL,
    CHQ_NO INTEGER NULL,
    CHQ_DATE SMALLDATETIME NULL,
    TXN_AMOUNT MONEY NOT NULL,
    USERID INTEGER NOT NULL,
    CONSTRAINT FK_TRANSACTION_ACCOUNT FOREIGN KEY (ACID) REFERENCES ACCOUNT_MASTER(ACID),
    CONSTRAINT FK_TRANSACTION_BRANCH FOREIGN KEY (BRID) REFERENCES BRANCH_MASTER(BRID),
    CONSTRAINT FK_TRANSACTION_USER FOREIGN KEY (USERID) REFERENCES USER_MASTER(USERID),
    CONSTRAINT CHK_TXN_TYPE CHECK (TXN_TYPE IN ('CW', 'CD', 'CQD'))
);
GO

-- Display confirmation message
PRINT 'Database "INDIAN BANK" and all tables have been created successfully!';
